### ISSUE TITLE
Allow community maintenance?

### ISSUE THREAD

**Issue by Pathoschild** [ThatNorthernMonkey/HarvestWithScythe#1]
Hi! I love this mod, but it seems to no longer be maintained. Would you be okay letting other modders take care of it while you're away? You'll still be credited as the original author, and can take it back anytime. See the [community maintenance FAQs](https://github.com/Pathoschild/StardewCommunityMods#faqs) for details.

If you're interested, you only need to:

1. [choose an open-source license](https://choosealicense.com/) for the code.
2. add `Pathoschild` as a team member on [the Nexus page](http://www.nexusmods.com/stardewvalley/mods/236/) so I can deploy updates. (From the mod page, click _Edit Attributes_ and search for "team members".)

From there the community can take care of the rest, which may include updating the code for the latest Stardew Valley/SMAPI releases, fixing any bugs, and maybe continuing development.

If you'd rather not do that, feel free to close this ticket. :)

**Comment by CraigWhitley** [comment]
Wow people are still using this? No worries, I'll let you in!

I've added you to it on Nexus mods, do I need to do anything on the Github end?

**Comment by Pathoschild** [comment]
Thanks! One last thing to do. Can you [choose an open-source license](https://choosealicense.com/), and [add the `LICENSE` file to the repository](https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository)?

**Comment by Pathoschild** [comment]
The community maintenance experiment unfortunately didn't work out, so this ticket is obsolete. We can still release unofficial updates if you add a `LICENSE` file though.
